# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-24 18:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BasisMetric',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Новая метрика', max_length=256, verbose_name='Название метрики')),
            ],
            options={
                'verbose_name_plural': 'Метрики для базисов',
                'verbose_name': 'Метрика для базисов',
            },
        ),
        migrations.CreateModel(
            name='BasisOfPsychotype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Новый базис', max_length=256, verbose_name='Название базиса психотипов')),
                ('description', models.TextField(default='', max_length=2048, verbose_name='Описание базиса психотипов.')),
                ('symptom_count', models.IntegerField(default=0, help_text='Длина булевого вектора.', verbose_name='Число признаков')),
                ('parameter_count', models.IntegerField(default=0, help_text='Длина вектора чисел.', verbose_name='Число параметров')),
                ('metric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='psychological_models.BasisMetric', verbose_name='Метрика')),
            ],
            options={
                'verbose_name_plural': 'Базисы психотипов',
                'verbose_name': 'Базис психотипов',
            },
        ),
    ]
